version: "3.4"

services:
  firebase:
    image: andreysenov/firebase-tools
    command: firebase emulators:start --project demo-es --only firestore
    network_mode: host
    ports:
      - 4000:4000 # emulator ui
      - 9099:9099 # auth emulator
      - 8087:8087 # firestore emulator
      - 8085:8085 # pubsub emulator
      - 9199:9199 # storage emulator
