version: "3.4"

services:
  # eventstore.db:
  #   image: eventstore/eventstore:21.10.2-buster-slim
  #   environment:
  #     - EVENTSTORE_CLUSTER_SIZE=1
  #     - EVENTSTORE_RUN_PROJECTIONS=All
  #     - EVENTSTORE_START_STANDARD_PROJECTIONS=true
  #     - EVENTSTORE_EXT_TCP_PORT=1113
  #     - EVENTSTORE_HTTP_PORT=2113
  #     - EVENTSTORE_INSECURE=true
  #     - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
  #     - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
  #   ports:
  #     - "1113:1113"
  #     - "2113:2113"
  #   volumes:
  #     - type: volume
  #       source: eventstore-volume-data
  #       target: /var/lib/eventstore
  #     - type: volume
  #       source: eventstore-volume-logs
  #       target: /var/log/eventstore

  firebase:
    image: andreysenov/firebase-tools
    command: firebase emulators:start --project demo-es --only firestore
    network_mode: host
    ports:
      - 4000:4000 # emulator ui
      - 9099:9099 # auth emulator
      - 8087:8087 # firestore emulator
      - 8085:8085 # pubsub emulator
      - 9199:9199 # storage emulator
    # volumes:
    #   - ./firebase.json:/home/node/firebase.json
    #   - ./firestore.rules:/home/node/firestore.rules
    #   - ./firestore.indexes.json:/home/node/firestore.indexes.json
    #   - ./storage.rules:/home/node/storage.rules

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
