name: Alpha

on:
  push:
    branches-ignore:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: "@ddd-ts"
      - run: yarn
      - run: yarn build
      - run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - run: npm version 0.0.0-feat.${{ github.ref_name }}.${SHORT_SHA} --workspaces
      - run: npm publish --access public --workspaces --tag feat.${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
